up:
	docker compose up -d

down:
	docker compose down

stop:
	docker compose stop

rebuild:
	docker compose up -d --build --remove-orphans

rebuild-hard:
	docker compose up -d --build --force-recreate --remove-orphans

ssh-api:
	docker compose exec api bash

init-db:
	docker compose exec api sh -c "./scripts/migrate.sh"